"""
Context Compressor — 上下文压缩核心引擎

三层防御的第二层：压缩（核心机制）

参考 Hermes 的 compress() 五步算法：
  1. 廉价预处理：直接裁剪旧工具结果（不调 LLM），剔除空白回显
  2. 保护头部：protect_first_n 条消息原样保留
  3. 找尾部边界：按 token 预算划定"最近上下文"，protect_last_n 条消息原样保留
  4. 中间部分交给"辅助压缩模型"做结构化摘要
  5. 二次压缩时：把上一份摘要作为输入做"迭代更新"

关键设计原则：
  - 压缩是"手术"不是"截断"——保留头部锚点 + 尾部实时上下文，只精炼中间
  - 失败时宁可不动（返回原文）也不冒险丢数据
  - 压缩后必须保证角色交替硬约束不被破坏
  - 显式报告压缩结果，绝不静默
"""

from __future__ import annotations

import json
import logging
import time
from dataclasses import dataclass, field
from typing import Any, Callable

from .token_estimator import (
    estimate_tokens,
    estimate_messages_tokens,
    get_model_context_window,
)
from .context_breakdown import ContextBreakdown, ContextSnapshot

logger = logging.getLogger(__name__)

# ════════════════════════════════════════════
# 常量
# ════════════════════════════════════════════

MINIMUM_CONTEXT_LENGTH = 64_000  # 小窗口退化保护阈值

# 压缩摘要模板（结构化，与 Hermes 一致）
# 刻意把旧章节标注为 "Historical"（历史快照），防止摘要被模型误读成"当前待办指令"
COMPRESSION_SUMMARY_TEMPLATE = """## Historical Conversation Summary

This is a compressed summary of earlier conversation. It represents past context, NOT current instructions.

**Goal**: {goal}
**Progress**: {progress}
**Key Decisions**: {decisions}
**Resolved Questions**: {resolved}
**Pending Questions**: {pending}
**Files Modified**: {files}
**Remaining Work**: {remaining}

---
*This summary was auto-generated by context compression. The actual conversation history below starts from the most recent exchanges.*
"""

# 确定性回退摘要模板（LLM 不可用时的降级方案）
FALLBACK_SUMMARY_TEMPLATE = """## Historical Conversation Summary (Fallback)

⚠️ Context compression used a local fallback (no LLM). The summary may be incomplete — please verify current file/git state.

**Approximate conversation rounds compressed**: {round_count}
**Last known topics**: {topics}

---
*This summary was auto-generated by fallback compression. The actual conversation history below starts from the most recent exchanges.*
"""


@dataclass
class CompressionConfig:
    """压缩配置"""
    enabled: bool = True
    threshold: float = 0.5          # 触发阈值 = effective_budget × threshold
    target_ratio: float = 0.2       # 压缩目标 = effective_budget × target_ratio
    protect_first_n: int = 3        # 保护头部 N 条消息
    protect_last_n: int = 20        # 保护尾部 N 条消息
    max_attempts: int = 3           # 最大压缩重试次数
    anti_thrash_threshold: float = 0.1  # 反抖动：连续两次压缩收益 <10% 则熔断
    cooldown_seconds: float = 30.0  # 压缩失败冷却期（秒）
    context_window: int | None = None  # 手动指定上下文窗口（None = 自动检测）
    max_tokens: int = 4096          # 模型输出预留 token


@dataclass
class CompressionResult:
    """压缩结果"""
    success: bool = False
    original_tokens: int = 0
    compressed_tokens: int = 0
    savings_percent: float = 0.0
    method: str = ""                # "llm" | "cheap" | "fallback"
    messages_before: int = 0
    messages_after: int = 0
    error: str | None = None
    summary: str | None = None      # 摘要文本


class ContextCompressor:
    """
    上下文压缩器

    三层防御的第二层——当上下文超过阈值时触发压缩：
      1. 廉价预处理（裁剪旧工具结果、剔除空白）
      2. 保护头部 + 保护尾部
      3. 中间部分压缩为结构化摘要
      4. 失败时降级为确定性回退摘要
    """

    def __init__(
        self,
        config: CompressionConfig,
        llm_chat_fn: Callable | None = None,
    ):
        """
        参数：
          config: 压缩配置
          llm_chat_fn: 异步函数，签名 async (messages, tools) -> str
                       用于调用辅助压缩模型生成摘要。
                       若为 None，则压缩降级为确定性回退。
        """
        self.config = config
        self._llm_chat_fn = llm_chat_fn
        self._last_compress_time = 0.0
        self._last_savings_percent = 0.0
        self._consecutive_low_savings = 0
        self._in_cooldown = False
        self._last_snapshot: ContextSnapshot | None = None

    @property
    def is_in_cooldown(self) -> bool:
        """是否在冷却期内"""
        if not self._in_cooldown:
            return False
        if time.time() - self._last_compress_time > self.config.cooldown_seconds:
            self._in_cooldown = False
        return self._in_cooldown

    def should_compress(
        self,
        messages: list[dict],
        tool_schemas: list[dict] | None = None,
        model_name: str = "",
    ) -> tuple[bool, ContextSnapshot]:
        """
        判断是否需要压缩（阈值判定）。

        返回 (should_compress, snapshot)
        逻辑与 Hermes should_compress 一致：
          阈值 = effective_budget × threshold%
          小窗口退化保护：若阈值 ≥ 整个窗口，改用窗口的 85%
          反抖动保护：连续两次压缩收益 <10% 时熔断
          冷却期保护：压缩失败后进入冷却
        """
        if not self.config.enabled:
            snapshot = self._build_snapshot(messages, tool_schemas, model_name)
            return False, snapshot

        snapshot = self._build_snapshot(messages, tool_schemas, model_name)
        self._last_snapshot = snapshot

        # 冷却期内不触发
        if self.is_in_cooldown:
            return False, snapshot

        # 反抖动保护
        if self._consecutive_low_savings >= 2:
            logger.info("Context compression: anti-thrash protection active "
                         "(consecutive low savings), skipping compression")
            return False, snapshot

        # 计算阈值
        threshold_tokens = int(snapshot.effective_budget * self.config.threshold)

        # 小窗口退化保护
        if threshold_tokens >= snapshot.context_window:
            threshold_tokens = int(snapshot.context_window * 0.85)
            logger.debug(f"Small window degradation: threshold adjusted to {threshold_tokens}")

        # 判定
        should = snapshot.total_tokens >= threshold_tokens
        if should:
            logger.info(
                f"Context compression triggered: {snapshot.total_tokens:,} tokens "
                f">= threshold {threshold_tokens:,} "
                f"({self.config.threshold:.0%} of {snapshot.effective_budget:,} budget)"
            )

        return should, snapshot

    async def compress(
        self,
        messages: list[dict],
        tool_schemas: list[dict] | None = None,
        model_name: str = "",
    ) -> tuple[list[dict], CompressionResult]:
        """
        执行压缩（5 步算法）。

        返回 (compressed_messages, result)
        压缩后必须保证：
          1. __meta__ 消息保留
          2. system 消息保留
          3. 角色交替硬约束不被破坏
          4. 孤儿 tool_call/tool_result 对被清理
        """
        original_tokens = estimate_messages_tokens(messages)
        meta_messages = [m for m in messages if m.get("role") == "__meta__"]
        chat_messages = [m for m in messages if m.get("role") != "__meta__"]

        if len(chat_messages) <= self.config.protect_first_n + self.config.protect_last_n:
            # 消息太少，不值得压缩
            return messages, CompressionResult(
                success=False,
                original_tokens=original_tokens,
                compressed_tokens=original_tokens,
                method="skipped",
                messages_before=len(messages),
                messages_after=len(messages),
                error="Too few messages to compress",
            )

        # ── Step 1: 廉价预处理（不调 LLM）──
        chat_messages = self._cheap_preprocess(chat_messages)
        cheap_tokens = estimate_messages_tokens(chat_messages)

        # ── Step 2: 保护头部（确保不拆散 tool_calls 配对）──
        head_end = self.config.protect_first_n
        head_end = self._align_tool_calls_boundary(chat_messages, head_end)
        head = chat_messages[:head_end]
        mid_and_tail = chat_messages[head_end:]

        # ── Step 3: 找尾部边界（确保不拆散 tool_calls 配对）──
        tail_start_raw = max(0, len(mid_and_tail) - self.config.protect_last_n)
        tail_start = self._align_tool_calls_boundary(mid_and_tail, tail_start_raw)
        tail = mid_and_tail[tail_start:]
        middle = mid_and_tail[:tail_start] if tail_start < len(mid_and_tail) else []

        if not middle:
            # 没有中间部分可压缩
            return messages, CompressionResult(
                success=False,
                original_tokens=original_tokens,
                compressed_tokens=cheap_tokens,
                method="cheap",
                messages_before=len(messages),
                messages_after=len(messages),
                error="No middle section to compress",
            )

        # ── Step 4: 压缩中间部分 ──
        summary_text, method, error = await self._compress_middle(middle, model_name)

        if not summary_text:
            # 压缩失败，返回廉价预处理后的结果
            result_messages = meta_messages + head + chat_messages[self.config.protect_first_n:]
            return result_messages, CompressionResult(
                success=False,
                original_tokens=original_tokens,
                compressed_tokens=estimate_messages_tokens(result_messages),
                method=method,
                messages_before=len(messages),
                messages_after=len(result_messages),
                error=error or "Compression produced no summary",
            )

        # ── Step 5: 组装压缩后的消息列表 ──
        # 摘要消息（user 角色，确保角色交替）
        summary_message = {
            "role": "user",
            "content": summary_text,
        }
        # 重新注入被压缩掉的技能标记
        pruned_skills = self._extract_pruned_skill_markers(middle)
        if pruned_skills:
            summary_message["content"] += f"\n\n[SKILL_PRUNED] {pruned_skills}"

        # 在摘要后面紧跟一条 assistant 确认，保证角色交替
        confirm_message = {
            "role": "assistant",
            "content": "[Context compressed — continuing from summary]",
        }

        compressed_messages = meta_messages + head + [summary_message, confirm_message] + tail

        # ── 清理孤儿 tool_call/tool_result ──
        compressed_messages = self._clean_orphan_tool_calls(compressed_messages)

        # ── 插入真实用户消息锚点（保证角色交替）──
        compressed_messages = self._insert_real_user_anchor(compressed_messages)

        # ── 再次清理：_insert_real_user_anchor 可能插入 user 消息后
        # 导致 tool 响应与 assistant(tool_calls) 之间出现新间隔，
        # 需要重新检测并清理可能的孤儿 ──
        compressed_messages = self._clean_orphan_tool_calls(compressed_messages)

        # ── 计算结果 ──
        compressed_tokens = estimate_messages_tokens(compressed_messages)
        savings = 0.0
        if original_tokens > 0:
            savings = (1 - compressed_tokens / original_tokens) * 100

        result = CompressionResult(
            success=True,
            original_tokens=original_tokens,
            compressed_tokens=compressed_tokens,
            savings_percent=savings,
            method=method,
            messages_before=len(messages),
            messages_after=len(compressed_messages),
            summary=summary_text[:200],
        )

        # ── 反抖动检测 ──
        if savings < self.config.anti_thrash_threshold * 100:
            self._consecutive_low_savings += 1
            logger.warning(f"Context compression low savings: {savings:.1f}% "
                            f"(consecutive: {self._consecutive_low_savings})")
        else:
            self._consecutive_low_savings = 0

        self._last_compress_time = time.time()
        logger.info(
            f"Context compression complete: {original_tokens:,} → {compressed_tokens:,} "
            f"tokens ({savings:.1f}% savings), method={method}"
        )

        return compressed_messages, result

    def _cheap_preprocess(self, messages: list[dict]) -> list[dict]:
        """
        Step 1: 廉价预处理（不调 LLM）

        - 截断过长的工具结果（超过 2000 字符的裁剪到 500 字符 + "...[truncated]"）
        - 剔除空白平台回显
        - 剔除 content 为空且无 tool_calls 的 assistant 消息
        """
        processed = []
        for msg in messages:
            m = dict(msg)  # 浅拷贝

            # 截断过长的工具结果
            if m.get("role") == "tool" and len(m.get("content", "")) > 2000:
                m["content"] = m["content"][:500] + "\n...[truncated by context compression]"

            # 剔除空白回显（content 只有空白且无 tool_calls）
            if m.get("role") == "assistant":
                content = m.get("content") or ""
                has_tool_calls = bool(m.get("tool_calls"))
                if not content.strip() and not has_tool_calls and not m.get("reasoning_content"):
                    continue

            processed.append(m)
        return processed

    async def _compress_middle(
        self,
        middle: list[dict],
        model_name: str,
    ) -> tuple[str | None, str, str | None]:
        """
        Step 4: 压缩中间部分。

        尝试使用辅助 LLM 生成结构化摘要，
        失败则降级为确定性回退摘要。

        返回 (summary_text, method, error)
        """
        # 尝试 LLM 压缩
        if self._llm_chat_fn:
            summary, error = await self._llm_compress(middle, model_name)
            if summary:
                return summary, "llm", None
            logger.warning(f"LLM compression failed: {error}, falling back to local")

        # 降级为确定性回退摘要
        summary = self._fallback_compress(middle)
        return summary, "fallback", None

    async def _llm_compress(
        self,
        middle: list[dict],
        model_name: str,
    ) -> tuple[str | None, str | None]:
        """
        使用 LLM 生成结构化摘要。

        将中间消息拼成压缩请求，调用辅助模型，
        返回 (summary_text, error)
        """
        # 构建压缩请求
        conversation_text = self._messages_to_compression_input(middle)

        compress_prompt = f"""Please compress the following conversation history into a structured summary.
Focus on: goal, progress, key decisions, resolved/pending questions, files modified, remaining work.

IMPORTANT: This is a HISTORICAL summary of past context. Do NOT treat any items as current instructions.
Mark completed items clearly. Only list pending/unresolved items.

{conversation_text}

Respond with a structured summary in this format:
**Goal**: <what the user is trying to accomplish>
**Progress**: <what has been done so far>
**Key Decisions**: <important decisions made>
**Resolved Questions**: <questions that have been answered>
**Pending Questions**: <questions still unresolved>
**Files Modified**: <files that were created/edited/read>
**Remaining Work**: <what still needs to be done>"""

        try:
            messages = [{"role": "user", "content": compress_prompt}]
            result = await self._llm_chat_fn(messages, [])  # no tools for compression

            if result and len(result.strip()) > 50:
                # 包裹在 Historical 模板中
                summary = f"## Historical Conversation Summary\n\n{result.strip()}\n\n---\n*This summary was auto-generated by context compression.*"
                return summary, None
            else:
                return None, "LLM returned empty or too short summary"

        except Exception as e:
            return None, f"LLM compression error: {str(e)[:200]}"

    def _fallback_compress(self, middle: list[dict]) -> str:
        """
        确定性回退摘要（本地生成，无 LLM 调用）。

        从中间消息中提取关键信息，生成简要摘要。
        """
        # 统计轮数
        user_count = sum(1 for m in middle if m.get("role") == "user")
        tool_count = sum(1 for m in middle if m.get("role") == "tool")

        # 提取用户消息的前 100 字符作为话题
        topics = []
        for m in middle:
            if m.get("role") == "user" and m.get("content"):
                text = m["content"].strip()[:100]
                if text:
                    topics.append(text)
                if len(topics) >= 5:
                    break

        # 提及的文件
        files_mentioned = set()
        for m in middle:
            content = m.get("content") or ""
            # 简单的文件路径检测
            import re
            for match in re.findall(r'[\w/\\-]+\.\w{1,10}', content):
                if len(match) > 5:
                    files_mentioned.add(match)

        topics_str = "; ".join(topics) if topics else "N/A"
        files_str = ", ".join(list(files_mentioned)[:10]) if files_mentioned else "None detected"

        summary = FALLBACK_SUMMARY_TEMPLATE.format(
            round_count=user_count,
            topics=topics_str,
        )

        if files_mentioned:
            summary += f"\n**Files mentioned in compressed section**: {files_str}\n"

        return summary

    def _messages_to_compression_input(self, messages: list[dict]) -> str:
        """将消息列表转为压缩输入文本"""
        lines = []
        for m in messages:
            role = m.get("role", "unknown")
            content = m.get("content") or ""

            if role == "user":
                lines.append(f"[User]: {content[:500]}")
            elif role == "assistant":
                if m.get("tool_calls"):
                    for tc in m["tool_calls"]:
                        func = tc.get("function", {})
                        lines.append(f"[Assistant → Tool]: {func.get('name', '?')}({func.get('arguments', '')[:200]})")
                if content:
                    lines.append(f"[Assistant]: {content[:500]}")
            elif role == "tool":
                name = m.get("name", "")
                lines.append(f"[Tool Result ({name})]: {content[:300]}")

        return "\n".join(lines)

    def _extract_pruned_skill_markers(self, messages: list[dict]) -> str:
        """从被压缩的消息中提取技能标记"""
        markers = set()
        for m in messages:
            content = m.get("content") or ""
            if "[SKILL_PRUNED]" in content:
                # 提取技能名
                import re
                matches = re.findall(r'\[SKILL_PRUNED\]\s*(.+?)(?:\n|$)', content)
                markers.update(matches)
        return ", ".join(markers) if markers else ""

    def _align_tool_calls_boundary(self, messages: list[dict], split_index: int) -> int:
        """
        调整切分索引，确保 assistant(tool_calls) 及其对应的 tool 响应
        不会被切分边界拆散。

        规则：如果 split_index 落在一组 tool_calls 配对内部，
        向前或向后移动索引直到配对完整。

        场景 A：head 末尾是 assistant(tool_calls)，后面的 tool 在 middle
          → 将 tool 响应一起拉入 head（split_index 后移）
        场景 B：tail 开头是 tool 响应，前面的 assistant(tool_calls) 在 middle
          → 将 assistant(tool_calls) 一起拉入 tail（split_index 前移）
        """
        if split_index <= 0 or split_index >= len(messages):
            return split_index

        # 场景 A：检查 split_index 前面是否有未配完的 tool_calls
        # 向前扫描，找到最近的 assistant(tool_calls)
        pending_call_ids = set()
        for i in range(split_index - 1, -1, -1):
            m = messages[i]
            if m.get("role") == "assistant" and m.get("tool_calls"):
                for tc in m["tool_calls"]:
                    tc_id = tc.get("id")
                    if tc_id:
                        pending_call_ids.add(tc_id)
                break  # 只看紧邻的 assistant
            elif m.get("role") == "tool":
                continue  # 跳过已有的 tool 消息
            else:
                break  # 其他角色，不需要继续

        # 如果有未配的 tool_calls，向后扩展 split_index 包含所有 tool 响应
        if pending_call_ids:
            found_ids = set()
            extend = 0
            assistant_index = None  # 记录 assistant(tool_calls) 的位置
            for i in range(split_index - 1, -1, -1):
                m = messages[i]
                if m.get("role") == "assistant" and m.get("tool_calls"):
                    assistant_index = i
                    break
                elif m.get("role") == "tool":
                    continue
                else:
                    break

            for i in range(split_index, len(messages)):
                m = messages[i]
                if m.get("role") == "tool" and m.get("tool_call_id") in pending_call_ids:
                    found_ids.add(m["tool_call_id"])
                    extend = i - split_index + 1
                elif m.get("role") == "tool":
                    continue  # 其他 tool 消息（同组或不同组）
                else:
                    break  # tool 响应序列结束
                if found_ids == pending_call_ids:
                    break

            if found_ids == pending_call_ids:
                # 全部 tool 响应都找到，向后扩展 head 包含它们
                split_index += extend
            elif assistant_index is not None and found_ids != pending_call_ids:
                # 部分 tool 响应缺失：不能把不完整的 assistant(tool_calls) 留在 head，
                # 否则 head 中的 assistant 带有没有响应的 tool_calls，发给 API 必报 400。
                # 将 split_index 前移到 assistant 之前，让整个 assistant+tool 组
                # 进入 middle 去压缩（_clean_orphan_tool_calls 会清理孤儿）。
                split_index = assistant_index

        # 场景 B：检查 split_index 处是否以 tool 响应开头（缺少 assistant）
        if split_index < len(messages) and messages[split_index].get("role") == "tool":
            # 找到这个 tool 响应所属的 assistant(tool_calls)
            orphan_tool_ids = set()
            for i in range(split_index, len(messages)):
                m = messages[i]
                if m.get("role") == "tool":
                    orphan_tool_ids.add(m.get("tool_call_id"))
                else:
                    break

            # 向前找到对应的 assistant(tool_calls)
            for i in range(split_index - 1, -1, -1):
                m = messages[i]
                if m.get("role") == "assistant" and m.get("tool_calls"):
                    has_match = any(
                        tc.get("id") in orphan_tool_ids for tc in m["tool_calls"]
                    )
                    if has_match:
                        split_index = i  # 将 assistant 一起拉入 tail
                    break
                elif m.get("role") == "tool":
                    continue
                else:
                    break

        return split_index

    def _clean_orphan_tool_calls(self, messages: list[dict]) -> list[dict]:
        """清理孤儿 tool_call/tool_result 对（双向清理）"""
        # 收集所有 tool_call_id
        call_ids = set()
        for m in messages:
            for tc in m.get("tool_calls", []):
                tc_id = tc.get("id")
                if tc_id:
                    call_ids.add(tc_id)

        # 收集所有 tool 消息的 tool_call_id
        result_ids = set()
        for m in messages:
            if m.get("role") == "tool" and m.get("tool_call_id"):
                result_ids.add(m["tool_call_id"])

        # 双向孤儿检测
        orphan_result_ids = result_ids - call_ids    # 有 tool 结果但无 tool_calls
        orphan_call_ids = call_ids - result_ids      # 有 tool_calls 但无 tool 结果

        if not orphan_result_ids and not orphan_call_ids:
            return messages

        cleaned = []
        for m in messages:
            # 删除无对应 tool_calls 的 tool 结果
            if m.get("role") == "tool" and m.get("tool_call_id") in orphan_result_ids:
                continue
            # 剥除无对应 tool 结果的 assistant(tool_calls) 的 tool_calls 字段
            # （保留消息本身但去掉 tool_calls，避免 API 报 400）
            if m.get("role") == "assistant" and m.get("tool_calls"):
                has_orphan = any(
                    tc.get("id") in orphan_call_ids for tc in m["tool_calls"]
                )
                if has_orphan:
                    # 如果所有 tool_calls 都是孤儿，直接去掉 tool_calls
                    surviving = [tc for tc in m["tool_calls"] if tc.get("id") not in orphan_call_ids]
                    if not surviving:
                        # 全部孤儿：去掉 tool_calls 字段，保留 content
                        m_copy = {k: v for k, v in m.items() if k != "tool_calls"}
                        if not m_copy.get("content"):
                            m_copy["content"] = ""
                        cleaned.append(m_copy)
                        continue
                    else:
                        # 部分孤儿：只保留有配对的 tool_calls
                        m_copy = dict(m)
                        m_copy["tool_calls"] = surviving
                        cleaned.append(m_copy)
                        continue
            cleaned.append(m)

        return cleaned

    def _insert_real_user_anchor(self, messages: list[dict]) -> list[dict]:
        """
        插入真实用户消息锚点，保证角色交替硬约束不被破坏。

        规则：不能出现两条 assistant 相邻。
        如果检测到这种情况，在两条 assistant 之间插入一条
        来自最近 user 消息的锚点。
        """
        if len(messages) <= 1:
            return messages

        result = [messages[0]]
        for i in range(1, len(messages)):
            prev_role = result[-1].get("role")
            curr_role = messages[i].get("role")

            # 两条 assistant 相邻 → 插入用户锚点
            if prev_role == "assistant" and curr_role == "assistant":
                # 找最近的用户消息内容
                anchor_content = "[continued conversation]"
                for j in range(i - 1, -1, -1):
                    if messages[j].get("role") == "user" and messages[j].get("content"):
                        anchor_content = messages[j]["content"][:100]
                        break

                result.append({
                    "role": "user",
                    "content": f"[Context anchor: {anchor_content}]",
                })

            result.append(messages[i])

        return result

    def _build_snapshot(
        self,
        messages: list[dict],
        tool_schemas: list[dict] | None,
        model_name: str,
    ) -> ContextSnapshot:
        """构建上下文快照"""
        return ContextBreakdown.capture(
            messages=messages,
            tool_schemas=tool_schemas,
            model_name=model_name,
            context_window=self.config.context_window,
            max_tokens=self.config.max_tokens,
        )

    def reset_thrash_counter(self) -> None:
        """重置反抖动计数器（通常在新会话开始时调用）"""
        self._consecutive_low_savings = 0
